version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:./node_modules
      - ./src:./src
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./node_modules:/node_modules
      - ./src:/src
    command: ["npm", "run", "test"]
